name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Get dependencies
        run: make deps
      - name: Build
        run: make
      - name: Test
        run: go test
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          # set github personal access token in order to generate brew formula to external repository
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
